CREATE TABLE TRAINER_POKEMON_COLLECTION (
	ID_TRAINER INT REFERENCES TRAINER (TRAINER_ID),
	ID_POKEMON INT REFERENCES POKEMON (POKEMON_ID),
	AQUISITION_DATE DATE,
	IS_FAVORITE BIT NOT NULL DEFAULT 0,
	CONSTRAINT TRAINER_POKEMON_COLLECTION_PKEY PRIMARY KEY (TRAINER_ID, POKEMON_ID)
);