CREATE TABLE `TRAINER_POKEMON_COLLECTION` (
	`ID_TRAINER_POKEMON_COLLECTION` INT NOT NULL AUTO_INCREMENT,
	`ID_TRAINER` INT NOT NULL,
	`ID_POKEMON` INT NOT NULL,
	`AQUISITION_DATE` DATETIME,
	UNIQUE KEY `PK_COLLECTION` (`ID_TRAINER_POKEMON_COLLECTION`) USING BTREE,
	PRIMARY KEY (`ID_TRAINER_POKEMON_COLLECTION`)
	FOREIGN KEY (`ID_TRAINER`,`ID_POKEMON`)
);