/* 
	script to MySQL 
	generate in: https://wtools.io/generate-sql-create-table
*/

CREATE TABLE `TRAINERS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(50) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
	`EMAIL` VARCHAR(255) NOT NULL,
	`NICKNAME` VARCHAR(50) NOT NULL,
	`IMAGE` TEXT,
	UNIQUE KEY `ID_UNIQUE` (`ID`) USING BTREE,
	UNIQUE KEY `NICKNAME_UNIQUE` (`NICKNAME`) USING BTREE,
	PRIMARY KEY (`ID`)
);
