CREATE TABLE IF NOT EXISTS api.pokemons
(
    "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		"NAME" varchar(255),
    "CATEGORY" varchar(30),
    "ABILITIES" varchar(255),  
    "HEIGHT" varchar(10),
		"WEIGHT" varchar(10),
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pokemons
    OWNER to pokemon;

-- POPULATE TABLE
INSERT INTO api.pokemons(
	"ID", "CATEGORY", "ABILITIES", "HEIGHT", "WEIGHT")
	VALUES
    (1, 'Bulbasaur', 'Seed', 'Overgrow', '0.7 m', '6.9 kg'),
    (2, 'Ivysaur', 'Seed', 'Overgrow', '1.0 m', '13.0 kg'),
		(3, 'Venusaur', 'Seed', 'Overgrow', '2.0 m', '100.0 kg'),
		(4, 'Charmander', 'Fire', 'Blaze', '0.6 m', '8.5 kg'),
		(5, 'Charmeleon', 'Fire', 'Blaze', '1.0 m', '19.0 kg'),
		(6, 'Charizard', 'Fire', 'Blaze', '1.7 m', '90.5 kg'),
		(7, 'Squirtle', 'Water', 'Torrent', '0.5 m', '9.0 kg'),
		(8, 'Wartortle', 'Water', 'Torrent', '1.0 m', '22.5 kg'),
		(9, 'Blastoise', 'Water', 'Torrent', '1.6 m', '85.5 kg'),
		(10, 'Caterpie', 'Bug', 'None', '0.3 m', '2.9 kg'),
		(11, 'Metapod', 'Bug', 'None', '0.7 m', '9.9 kg'),
		(12, 'Butterfree', 'Bug', 'None', '1.1 m', '32.0 kg'),
		(13, 'Weedle', 'Bug', 'None', '0.3 m', '3.2 kg'),
		(14, 'Kakuna', 'Bug', 'None', '0.6 m', '10.0 kg'),
		(15, 'Beedrill', 'Bug', 'None', '1.0 m', '29.5 kg'),


-- SEARCH TABLE
SELECT * FROM api.pokemons
ORDER BY "ID" ASC 