-- CREATE SCHEMA
CREATE SCHEMA IF NOT EXISTS api;
-- CREATE TABLES
CREATE TABLE IF NOT EXISTS api.POKEDEX (
    ID INT PRIMARY KEY NOT NULL,
    NICKNAME VARCHAR(150),
    PRIMARY_TYPE VARCHAR(50) NOT NULL,
    SECONDARY_TYPE VARCHAR(50),
    HEIGHT FLOAT,
    WEIGHT INT,
    BASE_EXP INT,
    HP INT,
    ATTACK INT,
    DEFENSE INT,
    SPECIAL_ATK INT,
    SPECIAL_DEF INT,
    SPEED INT,
    ARTWORK VARCHAR(512)
);
CREATE TABLE IF NOT EXISTS api.POKEMON (
    ID SERIAL PRIMARY KEY,
    NICKNAME VARCHAR(150),
    PRIMARY_TYPE VARCHAR(50) NOT NULL,
    SECONDARY_TYPE VARCHAR(50),
    HEIGHT FLOAT,
    WEIGHT INT,
    BASE_EXP INT,
    LEVEL INT NOT NULL,
    ARTWORK VARCHAR(512),
    ID_POKEDEX INT
);
CREATE TABLE IF NOT EXISTS api.TRAINER (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    ID_TEAM INT,
    ID_COLLECTION INT,
    NICKNAME VARCHAR(150) NOT NULL
);
CREATE TABLE IF NOT EXISTS api.COLLECTION (
    ID SERIAL PRIMARY KEY,
    ID_TRAINER INT NOT NULL,
    ID_POKEMON INT NOT NULL,
    IS_FAVORITE BOOLEAN,
    AQUISITION_DATE DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS api.TEAM (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    ID_TEAM_POKEMON INT
);
CREATE TABLE IF NOT EXISTS api.TEAM_POKEMON (
    ID SERIAL PRIMARY KEY,
    ID_TEAM INT NOT NULL,
    ID_POKEMON INT NOT NULL
);
-- UPDATE TABLE FOREIGN KEYS
ALTER TABLE api.POKEMON
ADD FOREIGN KEY(ID_POKEDEX) REFERENCES api.POKEDEX (ID);
ALTER TABLE api.TRAINER
ADD FOREIGN KEY(ID_TEAM) REFERENCES api.TEAM (ID);
ALTER TABLE api.TRAINER
ADD FOREIGN KEY(ID_COLLECTION) REFERENCES api.COLLECTION (ID);
ALTER TABLE api.COLLECTION
ADD FOREIGN KEY(ID_TRAINER) REFERENCES api.TRAINER (ID);
ALTER TABLE api.COLLECTION
ADD FOREIGN KEY(ID_POKEMON) REFERENCES api.POKEMON (ID);
ALTER TABLE api.TEAM
ADD FOREIGN KEY(ID_TEAM_POKEMON) REFERENCES api.TEAM_POKEMON (ID);
ALTER TABLE api.TEAM_POKEMON
ADD FOREIGN KEY(ID_TEAM) REFERENCES api.TEAM (ID);
ALTER TABLE api.TEAM_POKEMON
ADD FOREIGN KEY(ID_POKEMON) REFERENCES api.POKEMON (ID);