CREATE SCHEMA IF NOT EXISTS api;

CREATE TABLE IF NOT EXISTS api.POKEDEX (
    ID SERIAL PRIMARY KEY NOT NULL,
    NICKNAME VARCHAR(150),
    PRIMARY_TYPE VARCHAR(50) NOT NULL,
    SECONDARY_TYPE VARCHAR(50),
    HEIGHT FLOAT,
    WEIGHT INT,
    BASE_EXP INT,
    HP INT,
    ATTACK INT,
    DEFENSE INT,
    SPECIAL_ATK INT,
    SPECIAL_DEF INT,
    SPEED INT,
    ARTWORK VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS api.POKEMON (
    ID SERIAL PRIMARY KEY,
    NICKNAME VARCHAR(150),
    PRIMARY_TYPE VARCHAR(50) NOT NULL,
    SECONDARY_TYPE VARCHAR(50),
    HEIGHT FLOAT,
    WEIGHT INT,
    BASE_EXP INT,
    LEVEL INT NOT NULL,
    ARTWORK VARCHAR(512),
    ID_POKEDEX INT,
    CONSTRAINT FK_POKEDEX FOREIGN KEY(ID_POKEDEX) REFERENCES api.POKEDEX(ID)
);
